# build_py_schemas — precompute the input schema (cols/dtypes + a small sample) and the
# OUTPUT SHAPE (cols/dtypes/rowcount, NO values — preserves the trap pedagogy, D-PL-25/26)
# for every PyLab problem, into src/data/pyLabSchemas.js. Static at runtime → the two-pane
# schema panel + schema-name autocomplete are instant, zero Pyodide-on-open cost.
#
# Usage: node scripts/_extract_pylab.mjs /tmp/pyl.json && python3 scripts/build_py_schemas.py /tmp/pyl.json src/data/pyLabSchemas.js
import json, sys, os
import pandas as pd, numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _pylab_harness import _fresh, run_solution

data = json.load(open(sys.argv[1]))
problems, fixtures = data['problems'], data['fixtures']

def fmt(v):
    try:
        if v is None: return 'None'
        if isinstance(v, float) and pd.isna(v): return 'NaN'
    except Exception:
        pass
    s = str(v)
    return s if len(s) <= 28 else s[:26] + '…'

def cols(df):
    return [{'name': str(c), 'dtype': str(df[c].dtype)} for c in df.columns]

def describe_input(obj, name):
    if isinstance(obj, pd.DataFrame):
        rows = [[fmt(v) for v in r.tolist()] for _, r in obj.head(3).iterrows()]
        return {'name': name, 'kind': 'df', 'cols': cols(obj), 'rows': int(len(obj)), 'sample': rows}
    if isinstance(obj, pd.Series):
        return {'name': name, 'kind': 'series', 'dtype': str(obj.dtype), 'rows': int(len(obj)), 'sample': [fmt(v) for v in obj.head(5).tolist()]}
    if isinstance(obj, np.ndarray):
        return {'name': name, 'kind': 'ndarray', 'shape': list(obj.shape), 'dtype': str(obj.dtype), 'sample': [fmt(v) for v in obj.flatten()[:6].tolist()]}
    if isinstance(obj, (list, tuple)):
        return {'name': name, 'kind': 'list', 'length': len(obj), 'sample': [fmt(v) for v in list(obj)[:6]]}
    if isinstance(obj, dict):
        return {'name': name, 'kind': 'dict', 'keys': [str(k) for k in list(obj.keys())[:8]], 'length': len(obj)}
    return {'name': name, 'kind': 'scalar', 'repr': fmt(obj)}

def describe_output(obj):
    # SHAPE ONLY — never values
    if isinstance(obj, pd.DataFrame):
        return {'kind': 'df', 'cols': cols(obj), 'rows': int(len(obj))}
    if isinstance(obj, pd.Series):
        return {'kind': 'series', 'name': (str(obj.name) if obj.name is not None else None), 'dtype': str(obj.dtype), 'rows': int(len(obj))}
    if isinstance(obj, np.ndarray):
        return {'kind': 'ndarray', 'shape': list(obj.shape), 'dtype': str(obj.dtype)}
    if isinstance(obj, (list, tuple)):
        return {'kind': 'list', 'length': len(obj)}
    if isinstance(obj, dict):
        return {'kind': 'dict', 'length': len(obj)}
    return {'kind': 'scalar', 'type': type(obj).__name__}

out, errs = {}, 0
for p in problems:
    fx = fixtures.get(p.get('fixtureId'))
    if not fx:
        continue
    try:
        ns, _ = _fresh(fx)
        inputs = [describe_input(ns[a], a) for a in fx['args']]
        res = run_solution(p, fixtures)
        out[p['id']] = {'inputs': inputs, 'output': describe_output(res)}
    except Exception as e:
        out[p['id']] = {'inputs': [], 'output': None, 'err': str(e)[:90]}
        errs += 1

js = '// AUTO-GENERATED by scripts/build_py_schemas.py — do not edit by hand.\n'
js += '// Input schema (cols/dtypes + small sample) + OUTPUT SHAPE ONLY (no values, D-PL-26).\n'
js += 'export const pyLabSchemas = ' + json.dumps(out) + ';\nexport default pyLabSchemas;\n'
open(sys.argv[2], 'w').write(js)
print('wrote', len(out), 'schemas; errors:', errs)
if errs:
    for k, v in out.items():
        if v.get('err'):
            print('  ERR', k, v['err'])
